### ISSUE TITLE
Media quality control

### ISSUE THREAD

**Issue by ricardodalarme** [profusion/android-enhanced-video-player#50]
## Description

Provide a way for the user to change the quality of the video to a different resolution. It should read all the available qualities from the manifest (HLS, DASH, or MSS). It should also provide an `Auto` option if available.

## Acceptance criteria

- [x] The settings menu should have the option to change the quality
- [x] Qualities available should be fetched from the manifest
- [x] Qualities list should have an `Auto` option if available
- [x] Should be default on `Auto`

## Blocked by

- [x] https://github.com/profusion/android-enhanced-video-player/issues/60

**Comment by hspedro** [comment]
https://demo-streaming.gcdn.co/videos/676_YJHUNNocCsrjiCDx/master.m3u8

**Comment by aelnonym** [comment]
Deppends on #60

**Comment by hspedro** [comment]
S05: 05
S06: 01
