### ISSUE TITLE
[Spike] Exoplayer APIs for changing quality of video

### ISSUE THREAD

**Issue by hspedro** [profusion/android-enhanced-video-player#60]
## Spike/Research Request

Timebox: 1d

## Context

When using adaptive streaming algorithms, such as HLS, DASH, and MSS, the video manifest
comes with different bitrates to be played. Apart from showing them to the user, we must also
be able to change the quality of the track. Thus, we need to investigate how we change the video
quality using Exoplayer's API

## Knowledge Gap

* How to change track quality in Exoplayer
* How to enable `Auto` mode in Exoplayer

**Comment by aelnonym** [comment]
5 SP
The main challenge will be creating the track list correctly using [TrackGroup](https://developer.android.com/guide/topics/media/exoplayer/track-selection), with accurate labels and avoiding unnecessary recomposition. The `AUTO` mode is actually the default behavior if more than one track is provided for quality
