### ISSUE TITLE
Document Integration With React Native

### ISSUE THREAD

**Issue by hspedro** [profusion/android-enhanced-video-player#84]
## ➕ Enhancement Request 

Timebox: 5d

## Problem related to the enhancement request

We must document how this library can be integrated into a React Native project. This will improve how other people use the library and adjust any implementation details missing to guarantee compatibility with RN projects.

## Acceptance Criteria

- [ ] Create a markdown document explaining how to integrate our library with an RN project (Java Version, Gradle, AppCompat, XML, etc.)

**Comment by NatSatie** [comment]
Just to keep some notes, we need to think about how some parameters should fit in the Android version, for booleans seems to be something trivial.
As we can see [here](https://github.com/profusion/android-enhanced-video-player/blob/main/androidenhancedvideoplayer/src/main/java/com/profusion/androidenhancedvideoplayer/components/EnhancedVideoPlayer.kt)

```
zoomToFit: Boolean = true,
    enableImmersiveMode: Boolean = true,
    disableControls: Boolean = false,
    currentTimeTickInMs: Long = CURRENT_TIME_TICK_IN_MS,
    controlsVisibilityDurationInMs: Long = PLAYER_CONTROLS_VISIBILITY_DURATION_IN_MS,
    controlsCustomization: ControlsCustomization = ControlsCustomization(),
    transformSeekIncrementRatio: (tapCount: Int) -> Long = { it -> it * DEFAULT_SEEK_TIME_MS },
    previewThumbnailBuilder: ((timeInMillis: Long) -> ImageBitmap)? = null,
    settingsControlsCustomization: SettingsControlsCustomization = SettingsControlsCustomization()
```

Some parameters should receive some treatment, for example, Long variables, ControlsCustomization, and others
